[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "smartbay_marine_types_detection"
description = "AI-based marine types detection and classification algorithm based on YOLOv8"
readme = "README.md"
requires-python = ">=3.8"
license = { text = "AGPL-3.0-only"  }
classifiers = [
    "Intended Audience :: Information Technology",
    "Intended Audience :: AI/ML/DL Researchers",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
]
dynamic = ["version", "dependencies"]

# Add author and author email here
authors = [
  {name= "Fahimeh Alibabaei", email= "khadijeh.alibabaei@kit.edu"},
  {name= "Lisana Berberi", email= "lisana.berberi@kit.edu"},
  {name = "Damian Smyth", email = "datarequests@marine.ie"},
]

[project.urls]
"Homepage" = "https://github.com/ai4os-hub/smartbay-marine-types"
"Bug Tracker" = "https://github.com/ai4os-hub/smartbay-marine-types/issues"

[tool.pytest.ini_options]
pythonpath = ["."]
env = ["DATA_PATH=tests/data", "MODELS_PATH=tests/models"]
addopts = "--import-mode=importlib"

[tool.setuptools]
packages = ["yolov8_api", "smartbay_marine_types_detection.api"]

[tool.setuptools.package-dir]
"smartbay_marine_types_detection.api" = "api"
"yolov8_api" = "yolov8_api"

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }
version = { file = "VERSION" }

[project.entry-points."deepaas.v2.model"]
smartbay_marine_types_detection = "smartbay_marine_types_detection.api"